name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mathewspious/python-app:${{env.COMMIT_SHORT_SHA}}
    outputs:
      commit_id: ${{env.COMMIT_SHORT_SHA}}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Modify value file
        shell: bash
        run: | 
          echo ${{ needs.ci.outputs.commit_id }}
          curl -sSL -o ~/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x ~/yq
          sudo mv ~/yq /usr/local/bin/
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-app/values.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ needs.ci.outputs.commit_id }}'
      - name: Install Argo CD
        shell: bash
        run: |
          cd ~
          curl -ksSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/
      - name: Agrocd App Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure --grpc-web \
          --username admin --password ${{secrets.ARGOCD_SECRET}}
          argocd app sync python-app